### ISSUE TITLE
Mouse

### ISSUE THREAD

**Issue by Clay2419** [pyturtle/Overwatch2-colorbot-Cheats#4]
The arduino-contact sketch doesnt work for my steelseeries rival 710 mouse. is there any way to add a new sketch to make it work properly?

**Comment by pyturtle** [comment]
Are you using a USB host shield?

**Comment by pyturtle** [comment]
@Clay2419 You might be using the script wrong. The script should have no problems with any mice as it is just attached as a separate mouse. Like most games, overwatch does not suspect anything when you use two different mice to move.

**Comment by Clay2419** [comment]
i cant be using it wrong i just clicked the file and compiled and uploaded it. when i connect my mouse it doesnt turn on

**Comment by Clay2419** [comment]
@pyturtle Yeah its just not working on my mouse. Ive had issues with other sketches before too. I have some that work for other stuff.

**Comment by pyturtle** [comment]
@Clay2419 Are you plugging the mouse into the computer or arduino leonardo?

**Comment by Clay2419** [comment]
into the leaonardo board 
i also have the usb host shield attached

**Comment by pyturtle** [comment]
@Clay2419 I was trying to say in my first reply that for overwatch you don't need a host shield and you plug it into pc.

**Comment by Clay2419** [comment]
so just run the sketch and dont plug my mouse into the arduino? also how do i open the cheat or what buttons turn them on im kinda confused

**Comment by Clay2419** [comment]
@pyturtle also it says you have a runtime error : Bad magic number in .pyc file
