### ISSUE TITLE
Hey so i get this error

### ISSUE THREAD

**Issue by CryXE** [pyturtle/Overwatch2-colorbot-Cheats#8]
Traceback (most recent call last):
  File "C:\Users\danie\OneDrive\oc\Overwatch2-colorbot-Cheats-main\colorbot\main.py", line 16, in <module>
    serialcomm = serial.Serial('COM4',115200, timeout = 0)#com port for arduino
AttributeError: module 'serial' has no attribute 'Serial'
even though i did change it to the com

**Comment by pyturtle** [comment]
You most likely downloaded the wrong serial library.

**Comment by CryXE** [comment]
then what serial library do i gotta use?
